param(
    [ValidateSet("PreviewAll", "SendTestAll")]
    [string]$Mode,
    [string]$UserId,
    [string]$ConfigPath,
    [string]$ResultPath,
    [switch]$NoOpen
)

$ErrorActionPreference = "Stop"

if ($UserId -notmatch '^\d{1,20}$' -or ($Mode -eq "PreviewAll" -and -not $NoOpen)) {
    throw "The browser QA fixture accepts only fixed Manager operation contracts."
}

$config = Get-Content -LiteralPath $ConfigPath -Raw | ConvertFrom-Json
if ($config.FixtureOnly -ne $true) {
    throw "The browser QA fixture refuses non-fixture configuration."
}

Start-Sleep -Seconds 2

if ($Mode -eq "SendTestAll") {
    $testResult = [ordered]@{
        schemaVersion = 1
        mode = "SendTestAll"
        outcome = "succeeded"
        deliveryScope = "test"
        startedAtUtc = [DateTime]::UtcNow.AddSeconds(-2).ToString("o")
        finishedAtUtc = [DateTime]::UtcNow.ToString("o")
        durationMs = 2000
        smtpAcceptedCount = 6
        skippedCount = 0
        failedCount = 0
        generatedPreviewFiles = @()
    }
    [IO.File]::WriteAllText($ResultPath, (($testResult | ConvertTo-Json -Compress) + [Environment]::NewLine), (New-Object Text.UTF8Encoding($false)))
    exit 0
}

$output = Join-Path $PSScriptRoot "output"
New-Item -ItemType Directory -Path $output -Force | Out-Null

$states = @(
    @{ Number = "01"; Slug = "manual-welcome"; Title = "Manual welcome"; Copy = "A fictional first hello with no weekly statistics." },
    @{ Number = "02"; Slug = "new-user-no-history"; Title = "New user, no history"; Copy = "A mocked onboarding state with zero activity." },
    @{ Number = "03"; Slug = "new-user-with-history"; Title = "New user, with history"; Copy = "A mocked onboarding state with sample activity." },
    @{ Number = "04"; Slug = "normal-newsletter"; Title = "Established, active"; Copy = "A fictional weekly digest with sanitized titles." },
    @{ Number = "05"; Slug = "established-quiet"; Title = "Established, quiet"; Copy = "A mocked quiet-week state after warm-up." },
    @{ Number = "06"; Slug = "established-warmup"; Title = "Established, warming up"; Copy = "A mocked zero-activity state during warm-up." }
)

$style = @'
body{margin:0;background:#0b0c0c;color:#f6f4ef;font-family:Segoe UI,Arial,sans-serif}.shell{max-width:720px;margin:0 auto;padding:48px 24px}.label{color:#f8bd39;font-size:11px;font-weight:800;letter-spacing:2px;text-transform:uppercase}.card{margin-top:22px;padding:28px;border:1px solid #343536;border-radius:18px;background:linear-gradient(145deg,#181919,#101111)}h1{margin:9px 0;font-size:38px;letter-spacing:-1.5px}p{color:#aaa9a4;line-height:1.7}.items{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:24px}.item{min-height:92px;padding:16px;border-radius:12px;background:#202121}.item strong{display:block}.item small{display:block;margin-top:8px;color:#8e8f8a}@media(max-width:520px){.items{grid-template-columns:1fr}h1{font-size:30px}}
'@

foreach ($state in $states) {
    $document = @"
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>$($state.Title) - fictional QA preview</title><style>$style</style></head><body><main class="shell"><span class="label">Fictional browser QA fixture</span><section class="card"><span class="label">State $($state.Number) of 06</span><h1>$($state.Title)</h1><p>$($state.Copy) No real server, recipient, viewing history, or media metadata is represented.</p><div class="items"><article class="item"><strong>Signal at Sundown</strong><small>Fictional film · 2026</small></article><article class="item"><strong>Northstar Station</strong><small>Fictional series · Episode 4</small></article></div></section></main></body></html>
"@
    $name = "preview-all-$($state.Number)-$($state.Slug).html"
    Set-Content -LiteralPath (Join-Path $output $name) -Value $document -Encoding UTF8
}

$index = @"
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Fictional QA preview index</title><style>$style</style></head><body><main class="shell"><span class="label">Fictional browser QA fixture</span><section class="card"><h1>Six newsletter states</h1><p>This local index was generated by a reviewed fixture. It contacted no service and sent no email.</p></section></main></body></html>
"@
Set-Content -LiteralPath (Join-Path $output "preview-all-00-INDEX.html") -Value $index -Encoding UTF8

$result = [ordered]@{
    schemaVersion = 1
    mode = "PreviewAll"
    outcome = "succeeded"
    deliveryScope = "none"
    startedAtUtc = [DateTime]::UtcNow.AddSeconds(-2).ToString("o")
    finishedAtUtc = [DateTime]::UtcNow.ToString("o")
    durationMs = 2000
    smtpAcceptedCount = 0
    skippedCount = 0
    failedCount = 0
    generatedPreviewFiles = @(
        "preview-all-00-INDEX.html",
        "preview-all-01-manual-welcome.html",
        "preview-all-02-new-user-no-history.html",
        "preview-all-03-new-user-with-history.html",
        "preview-all-04-normal-newsletter.html",
        "preview-all-05-established-quiet.html",
        "preview-all-06-established-warmup.html"
    )
}
[IO.File]::WriteAllText($ResultPath, (($result | ConvertTo-Json -Compress) + [Environment]::NewLine), (New-Object Text.UTF8Encoding($false)))
